### ISSUE TITLE
Add @mvayngrib as a collaborator

### ISSUE THREAD

**Issue by nolanlawson** [No9/localstorage-down#73]
I'm +1 to add @mvayngrib as a collaborator based on recent PRs (#64, #65, #67), but I don't have the rights. @No9 if you're on board, could you do the honors?

As for rules, it's pretty informal, but I think generally it's good at ask for a +1 from someone else before merging code, although this repo has been pretty quiet, so sometimes you have to wait awhile. For less controversial stuff (readme fixes, etc.), those can just go in directly. And be sure to keep Travis green; once you have rights, you can restart jobs that fail spuriously.

Also @mvayngrib if you let me know your npm username I can add you as an owner, so you have `npm publish` rights.

**Comment by mvayngrib** [comment]
@nolanlawson thanks! i'm tenaciousmv on npm

**Comment by nolanlawson** [comment]
You're an owner now. Let's wait for all these PRs to get in before doing a release, though. Also I'm happy to do a release this time (seems to be a point release?).

**Comment by No9** [comment]
Sorry missed this
But I can see @mvayngrib in the npm store so taking it that we are all good.

**Comment by nolanlawson** [comment]
@No9 Did you add him as a collaborator in Github? I had the rights to add him to npm, but not Github.

**Comment by No9** [comment]
Have done now
Welcome @mvayngrib and thanks for the work

**Comment by mvayngrib** [comment]
@No9 my pleasure, thanks for adding
